export const languages = [
    { langCode: "af", name: "Afrikaans" },
    { langCode: "ar", name: "Arabic" },
    { langCode: "bn", name: "Bangla" },
    { langCode: "bs", name: "Bosnian (Latin)" },
    { langCode: "bg", name: "Bulgarian" },
    { langCode: "ca", name: "Catalan" },
    { langCode: "zh-Hans", name: "Chinese Simplified" },
    { langCode: "zh-Hant", name: "Chinese Traditional" },
    { langCode: "hr", name: "Croatian" },
    { langCode: "cs", name: "Czech" },
    { langCode: "da", name: "Danish" },
    { langCode: "nl", name: "Dutch" },
    { langCode: "en", name: "English" },
    { langCode: "fi", name: "Finnish" },
    { langCode: "fr", name: "French" },
    { langCode: "el", name: "Greek" },
    { langCode: "ht", name: "Haitian Creole" },
    { langCode: "hi", name: "Hindi" },
    { langCode: "hu", name: "Hungarian" },
    { langCode: "is", name: "Icelandic" },
    { langCode: "id", name: "Indonesian" },
    { langCode: "it", name: "Italian" },
    { langCode: "ja", name: "Japanese" },
    { langCode: "ko", name: "Korean" },
    { langCode: "lv", name: "Latvian" },
    { langCode: "lt", name: "Lithuanian" },
    { langCode: "mt", name: "Maltese" },
    { langCode: "de", name: "German" },
    { langCode: "nb", name: "Norwegian" },
    { langCode: "fa", name: "Persian" },
    { langCode: "pl", name: "Polish" },
    { langCode: "pt", name: "Portuguese (Brazil)" },
    { langCode: "ru", name: "Russian" },
    { langCode: "sr-Latn", name: "Serbian (Latin)" },
    { langCode: "sk", name: "Slovak" },
    { langCode: "sl", name: "Slovenian" },
    { langCode: "es", name: "Spanish" },
    { langCode: "sv", name: "Swedish" },
    { langCode: "tr", name: "Turkish" },
    { langCode: "th", name: "Thai" },
    { langCode: "uk", name: "Ukrainian" },
    { langCode: "ur", name: "Urdu" },
    { langCode: "vi", name: "Vietnamese" },
    { langCode: "cy", name: "Welsh" }
];

export const languageCodes = [
    "af", "sq", "am", "ar", "hy", "as", "az", "bn", "ba", "eu", "bho",
    "brx", "bs", "bg", "yue", "ca", "lzh", "zh-Hans", "zh-Hant", "sn",
    "hr", "cs", "da", "prs", "dv", "doi", "nl", "en", "et", "fo", "fj",
    "fil", "fi", "fr", "fr-ca", "gl", "ka", "de", "el", "gu", "ht", "ha",
    "he", "hi", "mww", "hu", "is", "ig", "id", "ikt", "iu", "iu-Latn",
    "ga", "it", "ja", "kn", "ks", "kk", "km", "rw", "tlh-Latn", "tlh-Piqd",
    "gom", "ko", "ku", "kmr", "ky", "lo", "lv", "lt", "ln", "dsb", "lug",
    "mk", "mai", "mg", "ms", "ml", "mt", "mi", "mr", "mn-Cyrl", "mn-Mong",
    "my", "ne", "nb", "nya", "or", "ps", "fa", "pl", "pt", "pt-pt", "pa",
    "otq", "ro", "run", "ru", "sm", "sr-Cyrl", "sr-Latn", "st", "nso",
    "tn", "sd", "si", "sk", "sl", "so", "es", "sw", "sv", "ty", "ta",
    "tt", "te", "th", "bo", "ti", "to", "tr", "tk", "uk", "hsb", "ur",
    "ug", "uz", "vi", "cy", "xh", "yo", "yua", "zu"
] as const;
