export const languages = [
    { langCode: "af", name: "Afrikaans" },
    { langCode: "ar", name: "Arabic" },
    { langCode: "bn", name: "Bangla" },
    { langCode: "bs", name: "Bosnian (Latin)" },
    { langCode: "bg", name: "Bulgarian" },
    { langCode: "ca", name: "Catalan" },
    { langCode: "zh-Hans", name: "Chinese Simplified" },
    { langCode: "zh-Hant", name: "Chinese Traditional" },
    { langCode: "hr", name: "Croatian" },
    { langCode: "cs", name: "Czech" },
    { langCode: "da", name: "Danish" },
    { langCode: "nl", name: "Dutch" },
    { langCode: "en", name: "English" },
    { langCode: "fi", name: "Finnish" },
    { langCode: "fr", name: "French" },
    { langCode: "el", name: "Greek" },
    { langCode: "ht", name: "Haitian Creole" },
    { langCode: "hi", name: "Hindi" },
    { langCode: "hu", name: "Hungarian" },
    { langCode: "is", name: "Icelandic" },
    { langCode: "id", name: "Indonesian" },
    { langCode: "it", name: "Italian" },
    { langCode: "ja", name: "Japanese" },
    { langCode: "ko", name: "Korean" },
    { langCode: "lv", name: "Latvian" },
    { langCode: "lt", name: "Lithuanian" },
    { langCode: "mt", name: "Maltese" },
    { langCode: "de", name: "German" },
    { langCode: "nb", name: "Norwegian" },
    { langCode: "fa", name: "Persian" },
    { langCode: "pl", name: "Polish" },
    { langCode: "pt", name: "Portuguese (Brazil)" },
    { langCode: "ru", name: "Russian" },
    { langCode: "sr-Latn", name: "Serbian (Latin)" },
    { langCode: "sk", name: "Slovak" },
    { langCode: "sl", name: "Slovenian" },
    { langCode: "es", name: "Spanish" },
    { langCode: "sv", name: "Swedish" },
    { langCode: "tr", name: "Turkish" },
    { langCode: "th", name: "Thai" },
    { langCode: "uk", name: "Ukrainian" },
    { langCode: "ur", name: "Urdu" },
    { langCode: "vi", name: "Vietnamese" },
    { langCode: "cy", name: "Welsh" }
];



export const langToLocaleMap = {
    af: "af-ZA",
    ar: "ar-SA",
    bn: "bn-IN",
    bs: "bs-BA",
    bg: "bg-BG",
    ca: "ca-ES",
    "zh-Hans": "zh-CN", // Simplified Chinese
    "zh-Hant": "zh-TW", // Traditional Chinese
    hr: "hr-HR",
    cs: "cs-CZ",
    da: "da-DK",
    nl: "nl-NL",
    en: "en-US", // fallback, could be en-GB too
    fi: "fi-FI",
    fr: "fr-FR",
    el: "el-GR",
    ht: "ht-HT",
    hi: "hi-IN",
    hu: "hu-HU",
    is: "is-IS",
    id: "id-ID",
    it: "it-IT",
    ja: "ja-JP",
    ko: "ko-KR",
    lv: "lv-LV",
    lt: "lt-LT",
    mt: "mt-MT",
    de: "de-DE",
    nb: "nb-NO",
    fa: "fa-IR",
    pl: "pl-PL",
    pt: "pt-BR",
    ru: "ru-RU",
    "sr-Latn": "sr-RS",
    sk: "sk-SK",
    sl: "sl-SI",
    es: "es-ES",
    sv: "sv-SE",
    tr: "tr-TR",
    th: "th-TH",
    uk: "uk-UA",
    ur: "ur-PK",
    vi: "vi-VN",
    cy: "cy-GB",
} as const

export const languageCodes = [
    "af", "ar", "bn", "bs", "bg", "ca", "zh-Hans", "zh-Hant", "hr", "cs", "da",
    "nl", "en", "fi", "fr", "el", "ht", "hi", "hu", "is", "id", "it", "ja", "ko",
    "lv", "lt", "mt", "de", "nb", "fa", "pl", "pt", "ru", "sr-Latn", "sk", "sl",
    "es", "sv", "tr", "th", "uk", "ur", "vi", "cy"
] as const;