export const users = [
    {
        username: "laci13",
        email: "laci13@gmail.com",
        password: "asd123",
        name: "Nagy László",
        roles: ["user"],
    },
    {
        username: "zoli88",
        email: "zoli88@gmail.com",
        password: "qwe456",
        name: "Kovács Zoltán",
        roles: ["user"],
    },
    {
        username: "anna92",
        email: "anna92@gmail.com",
        password: "zxc789",
        name: "Szabó Anna",
        roles: ["user"],
    },
    {
        username: "peter77",
        email: "peter77@gmail.com",
        password: "poi098",
        name: "Tóth Péter",
        roles: ["user"],
    },
    {
        username: "kata55",
        email: "kata55@gmail.com",
        password: "lkj321",
        name: "Horváth Katalin",
        roles: ["user"],
    }
    ,
    {
        username: "maria44",
        email: "maria44@gmail.com",
        password: "mnb789",
        name: "Kiss Mária",
        roles: ["user"],
    },
    {
        username: "istvan99",
        email: "istvan99@gmail.com",
        password: "jkl012",
        name: "Varga István",
        roles: ["user"],
    },
    {
        username: "eva22",
        email: "eva22@gmail.com",
        password: "hgf345",
        name: "Molnár Éva",
        roles: ["user"],
    },
    {
        username: "balazs66",
        email: "balazs66@gmail.com",
        password: "vbn678",
        name: "Farkas Balázs",
        roles: ["user"],
    }
    ,
    {
        username: "gabor11",
        email: "gabor11@gmail.com",
        password: "qaz147",
        name: "Szilágyi Gábor",
        roles: ["user"],
    },
    {
        username: "julia33",
        email: "julia33@gmail.com",
        password: "wsx258",
        name: "Németh Júlia",
        roles: ["user"],
    },
    {
        username: "tamas00",
        email: "tamas00@gmail.com",
        password: "edc369",
        name: "Papp Tamás",
        roles: ["user"],
    },
    {
        username: "zsuzsa77",
        email: "zsuzsa77@gmail.com",
        password: "rfv741",
        name: "Takács Zsuzsanna",
        roles: ["user"],
    },
    {
        username: "ferenc55",
        email: "ferenc55@gmail.com",
        password: "tgb852",
        name: "Lukács Ferenc",
        roles: ["user"],
    }
    ,
    {
        username: "robert44",
        email: "robert44@gmail.com",
        password: "yui963",
        name: "Balogh Róbert",
        roles: ["user"],
    },
    {
        username: "ildiko88",
        email: "ildiko88@gmail.com",
        password: "iop741",
        name: "Simon Ildikó",
        roles: ["user"],
    },
    {
        username: "laszlo22",
        email: "laszlo22@gmail.com",
        password: "asd852",
        name: "Király László",
        roles: ["user"],
    },
    {
        username: "eszter99", // REMOVED from class
        email: "eszter99@gmail.com",
        password: "qwe159",
        name: "Fekete Eszter",
        roles: ["user"],
    },
    {
        username: "andras77",
        email: "andras77@gmail.com",
        password: "zxc753",
        name: "Boros András",
        roles: ["user"],
    },
    {
        username: "klara55",
        email: "klara55@gmail.com",
        password: "poi456",
        name: "Gál Klára",
        roles: ["user"],
    },
    {
        username: "mate33",
        email: "mate33@gmail.com",
        password: "lkj789",
        name: "Sándor Máté",
        roles: ["user"],
    },
    {
        username: "dora11",
        email: "dora11@gmail.com",
        password: "mnb321",
        name: "Rácz Dóra",
        roles: ["user"],
    },
    {
        username: "norbert66",
        email: "norbert66@gmail.com",
        password: "jkl654",
        name: "Orosz Norbert",
        roles: ["user"],
    },
    {
        username: "vivien00",
        email: "vivien00@gmail.com",
        password: "hgf987",
        name: "Török Vivien",
        roles: ["user"],
    },
    {
        username: "csaba44",
        email: "csaba44@gmail.com",
        password: "vbn258",
        name: "Mészáros Csaba",
        roles: ["user"],
    },
    {
        username: "monika88",
        email: "monika88@gmail.com",
        password: "qaz369",
        name: "Hegedüs Monika",
        roles: ["user"],
    },
    {
        username: "attila22",
        email: "attila22@gmail.com",
        password: "wsx147",
        name: "Juhász Attila",
        roles: ["user"],
    },
    {
        username: "rita99",
        email: "rita99@gmail.com",
        password: "edc258",
        name: "Vincze Rita",
        roles: ["user"],
    },
    {
        username: "geza77",
        email: "geza77@gmail.com",
        password: "rfv963",
        name: "Kocsis Géza",
        roles: ["user"],
    }
]
